package minefantasy.mfr.recipe;

import minefantasy.mfr.api.crafting.Salvage;
import minefantasy.mfr.init.MineFantasyItems;
import minefantasy.mfr.item.ItemMetalComponent;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;

public class SalvageRecipes {
	public static void init() {
		ItemStack ironHunk = ((ItemMetalComponent)MineFantasyItems.METAL_HUNK).createComponentItemStack("iron");
		Salvage.addSalvage(Items.WOODEN_PICKAXE, new ItemStack(Items.STICK, 2), new ItemStack(Blocks.PLANKS, 3));
		Salvage.addSalvage(Items.WOODEN_AXE, new ItemStack(Items.STICK, 2), new ItemStack(Blocks.PLANKS, 3));
		Salvage.addSalvage(Items.WOODEN_SHOVEL, new ItemStack(Items.STICK, 2), new ItemStack(Blocks.PLANKS, 1));
		Salvage.addSalvage(Items.WOODEN_HOE, new ItemStack(Items.STICK, 2), new ItemStack(Blocks.PLANKS, 2));
		Salvage.addSalvage(Items.WOODEN_SWORD, new ItemStack(Items.STICK, 1), new ItemStack(Blocks.PLANKS, 2));

		Salvage.addSalvage(Items.STONE_PICKAXE, new ItemStack(Items.STICK, 2), new ItemStack(Blocks.COBBLESTONE, 3));
		Salvage.addSalvage(Items.STONE_AXE, new ItemStack(Items.STICK, 2), new ItemStack(Blocks.COBBLESTONE, 3));
		Salvage.addSalvage(Items.STONE_SHOVEL, new ItemStack(Items.STICK, 2), new ItemStack(Blocks.COBBLESTONE, 1));
		Salvage.addSalvage(Items.STONE_HOE, new ItemStack(Items.STICK, 2), new ItemStack(Blocks.COBBLESTONE, 2));
		Salvage.addSalvage(Items.STONE_SWORD, new ItemStack(Items.STICK, 1), new ItemStack(Blocks.COBBLESTONE, 2));

		Salvage.addSalvage(Items.LEATHER_HELMET, new ItemStack(Items.LEATHER, 5));
		Salvage.addSalvage(Items.LEATHER_CHESTPLATE, new ItemStack(Items.LEATHER, 8));
		Salvage.addSalvage(Items.LEATHER_LEGGINGS, new ItemStack(Items.LEATHER, 7));
		Salvage.addSalvage(Items.LEATHER_BOOTS, new ItemStack(Items.LEATHER, 4));

		Salvage.addSalvage(Items.IRON_PICKAXE, new ItemStack(Items.STICK, 2), new ItemStack(Items.IRON_INGOT, 3));
		Salvage.addSalvage(Items.IRON_AXE, new ItemStack(Items.STICK, 2), new ItemStack(Items.IRON_INGOT, 3));
		Salvage.addSalvage(Items.IRON_SHOVEL, new ItemStack(Items.STICK, 2), new ItemStack(Items.IRON_INGOT, 1));
		Salvage.addSalvage(Items.IRON_HOE, new ItemStack(Items.STICK, 2), new ItemStack(Items.IRON_INGOT, 2));
		Salvage.addSalvage(Items.IRON_SWORD, new ItemStack(Items.STICK, 1), new ItemStack(Items.IRON_INGOT, 2));
		Salvage.addSalvage(Items.CHAINMAIL_HELMET, new ItemStack(Items.IRON_INGOT, 2));
		Salvage.addSalvage(Items.CHAINMAIL_CHESTPLATE, new ItemStack(Items.IRON_INGOT, 4));
		Salvage.addSalvage(Items.CHAINMAIL_LEGGINGS, new ItemStack(Items.IRON_INGOT, 4));
		Salvage.addSalvage(Items.CHAINMAIL_BOOTS, new ItemStack(Items.IRON_INGOT, 2));
		Salvage.addSalvage(Items.IRON_HELMET, new ItemStack(Items.IRON_INGOT, 5));
		Salvage.addSalvage(Items.IRON_CHESTPLATE, new ItemStack(Items.IRON_INGOT, 8));
		Salvage.addSalvage(Items.IRON_LEGGINGS, new ItemStack(Items.IRON_INGOT, 7));
		Salvage.addSalvage(Items.IRON_BOOTS, new ItemStack(Items.IRON_INGOT, 4));
		Salvage.addSalvage(Items.IRON_HORSE_ARMOR, Items.LEATHER, new ItemStack(Items.IRON_INGOT, 8));

		Salvage.addSalvage(Items.GOLDEN_PICKAXE, new ItemStack(Items.STICK, 2), new ItemStack(Items.GOLD_INGOT, 3));
		Salvage.addSalvage(Items.GOLDEN_AXE, new ItemStack(Items.STICK, 2), new ItemStack(Items.GOLD_INGOT, 3));
		Salvage.addSalvage(Items.GOLDEN_SHOVEL, new ItemStack(Items.STICK, 2), new ItemStack(Items.GOLD_INGOT, 1));
		Salvage.addSalvage(Items.GOLDEN_HOE, new ItemStack(Items.STICK, 2), new ItemStack(Items.GOLD_INGOT, 2));
		Salvage.addSalvage(Items.GOLDEN_SWORD, new ItemStack(Items.STICK, 1), new ItemStack(Items.GOLD_INGOT, 2));
		Salvage.addSalvage(Items.GOLDEN_HELMET, new ItemStack(Items.GOLD_INGOT, 5));
		Salvage.addSalvage(Items.GOLDEN_CHESTPLATE, new ItemStack(Items.GOLD_INGOT, 8));
		Salvage.addSalvage(Items.GOLDEN_LEGGINGS, new ItemStack(Items.GOLD_INGOT, 7));
		Salvage.addSalvage(Items.GOLDEN_BOOTS, new ItemStack(Items.GOLD_INGOT, 4));
		Salvage.addSalvage(Items.GOLDEN_HORSE_ARMOR, Items.LEATHER, new ItemStack(Items.GOLD_INGOT, 8));

		Salvage.addSalvage(Items.DIAMOND_PICKAXE, new ItemStack(Items.STICK, 2), new ItemStack(Items.DIAMOND, 3));
		Salvage.addSalvage(Items.DIAMOND_AXE, new ItemStack(Items.STICK, 2), new ItemStack(Items.DIAMOND, 3));
		Salvage.addSalvage(Items.DIAMOND_SHOVEL, new ItemStack(Items.STICK, 2), new ItemStack(Items.DIAMOND, 1));
		Salvage.addSalvage(Items.DIAMOND_HOE, new ItemStack(Items.STICK, 2), new ItemStack(Items.DIAMOND, 2));
		Salvage.addSalvage(Items.DIAMOND_SWORD, new ItemStack(Items.STICK, 1), new ItemStack(Items.DIAMOND, 2));
		Salvage.addSalvage(Items.DIAMOND_HELMET, new ItemStack(Items.DIAMOND, 5));
		Salvage.addSalvage(Items.DIAMOND_CHESTPLATE, new ItemStack(Items.DIAMOND, 8));
		Salvage.addSalvage(Items.DIAMOND_LEGGINGS, new ItemStack(Items.DIAMOND, 7));
		Salvage.addSalvage(Items.DIAMOND_BOOTS, new ItemStack(Items.DIAMOND, 4));
		Salvage.addSalvage(Items.DIAMOND_HORSE_ARMOR, Items.LEATHER, new ItemStack(Items.DIAMOND, 8));

		Salvage.addSalvage(Items.FLINT_AND_STEEL, Items.FLINT, Items.IRON_INGOT);
		Salvage.addSalvage(Items.COMPASS, Items.REDSTONE, new ItemStack(Items.IRON_INGOT, 4));
		Salvage.addSalvage(Items.CLOCK, Items.REDSTONE, new ItemStack(Items.GOLD_INGOT, 4));
		Salvage.addSalvage(Items.BOW, new ItemStack(Items.STICK, 3), new ItemStack(Items.STRING, 3));
		Salvage.addSalvage(Items.FISHING_ROD, new ItemStack(Items.STICK, 3), new ItemStack(Items.STRING, 2));
		Salvage.addSalvage(Items.SHEARS, new ItemStack(Items.IRON_INGOT, 2));
		Salvage.addSalvage(Items.MINECART, new ItemStack(Items.IRON_INGOT, 5));
		Salvage.addSalvage(Items.BOAT, new ItemStack(Blocks.PLANKS, 5));

		Salvage.addSalvage(Blocks.FURNACE, new ItemStack(Blocks.COBBLESTONE, 8));
		Salvage.addSalvage(Blocks.DISPENSER, Items.BOW, Items.REDSTONE, new ItemStack(Blocks.COBBLESTONE, 7));
		Salvage.addSalvage(Blocks.DROPPER, Items.REDSTONE, new ItemStack(Blocks.COBBLESTONE, 7));
		Salvage.addSalvage(Blocks.CHEST, new ItemStack(Blocks.PLANKS, 8));
		Salvage.addSalvage(Blocks.PISTON, Items.REDSTONE, Items.IRON_INGOT, new ItemStack(Blocks.COBBLESTONE, 4), new ItemStack(Blocks.PLANKS, 3));
		Salvage.addSalvage(Blocks.STICKY_PISTON, Items.SLIME_BALL, Blocks.PISTON);
		Salvage.addSalvage(Items.OAK_DOOR, new ItemStack(Blocks.PLANKS, 6));
		Salvage.addSalvage(Items.SPRUCE_DOOR, new ItemStack(Blocks.PLANKS, 6));
		Salvage.addSalvage(Items.BIRCH_DOOR, new ItemStack(Blocks.PLANKS, 6));
		Salvage.addSalvage(Items.DARK_OAK_DOOR, new ItemStack(Blocks.PLANKS, 6));
		Salvage.addSalvage(Items.JUNGLE_DOOR, new ItemStack(Blocks.PLANKS, 6));
		Salvage.addSalvage(Items.ACACIA_DOOR, new ItemStack(Blocks.PLANKS, 6));
		Salvage.addSalvage(Items.IRON_DOOR, new ItemStack(Items.IRON_INGOT, 6));
		Salvage.addSalvage(Blocks.TRAPDOOR, new ItemStack(Blocks.PLANKS, 3));
		Salvage.addSalvage(Blocks.HOPPER, Blocks.CHEST, new ItemStack(Items.IRON_INGOT, 5));
		Salvage.addSalvage(Items.CAULDRON, new ItemStack(Items.IRON_INGOT, 7));
		Salvage.addSalvage(Items.BED, new ItemStack(Blocks.PLANKS, 3), new ItemStack(Blocks.WOOL, 3));
		Salvage.addSalvage(Items.BOOK, new ItemStack(Items.PAPER, 3), Items.LEATHER);
		Salvage.addSalvage(Items.BREWING_STAND, new ItemStack(Blocks.COBBLESTONE, 3), Items.BLAZE_ROD);
		Salvage.addSalvage(Items.CARROT_ON_A_STICK, Items.CARROT, Items.FISHING_ROD);
		Salvage.addSalvage(Items.COMPARATOR, new ItemStack(Blocks.REDSTONE_TORCH, 3), new ItemStack(Blocks.STONE, 3), Items.QUARTZ);
		Salvage.addSalvage(Items.ENDER_EYE, Items.ENDER_PEARL, Items.BLAZE_POWDER);
		Salvage.addSalvage(Items.MAGMA_CREAM, Items.BLAZE_POWDER, Items.SLIME_BALL);
		Salvage.addSalvage(Items.PAINTING, new ItemStack(Items.STICK, 8), Blocks.WOOL);
		Salvage.addSalvage(Items.REPEATER, new ItemStack(Blocks.STONE, 3), new ItemStack(Blocks.REDSTONE_TORCH, 2), Items.REDSTONE);
		Salvage.addSalvage(Items.SADDLE, Items.LEATHER, 5);
		Salvage.addSalvage(Items.SIGN, new ItemStack(Blocks.PLANKS, 2));
		Salvage.addSalvage(Items.SPECKLED_MELON, new ItemStack(Items.GOLD_NUGGET, 8), Items.MELON);
		Salvage.addSalvage(Blocks.ACTIVATOR_RAIL, Items.IRON_INGOT, Items.REDSTONE);
		Salvage.addSalvage(Blocks.ANVIL, new ItemStack(Items.IRON_INGOT, 31));
		Salvage.addSalvage(Blocks.BEACON, Items.NETHER_STAR, new ItemStack(Blocks.GLASS, 5), new ItemStack(Blocks.OBSIDIAN, 3));
		Salvage.addSalvage(Blocks.BOOKSHELF, new ItemStack(Blocks.PLANKS, 6), new ItemStack(Items.BOOK, 3));
		Salvage.addSalvage(Blocks.CRAFTING_TABLE, new ItemStack(Blocks.PLANKS, 4));
		Salvage.addSalvage(Blocks.DAYLIGHT_DETECTOR, new ItemStack(Blocks.GLASS, 3), new ItemStack(Blocks.WOODEN_SLAB, 3), new ItemStack(Items.QUARTZ, 3));
		Salvage.addSalvage(Blocks.DEADBUSH, new ItemStack(Items.STICK, 4));
		Salvage.addSalvage(Blocks.DETECTOR_RAIL, Blocks.RAIL, Blocks.STONE_PRESSURE_PLATE);
		Salvage.addSalvage(Blocks.ENCHANTING_TABLE, new ItemStack(Blocks.OBSIDIAN, 4), new ItemStack(Items.DIAMOND, 2), Items.BOOK);
		Salvage.addSalvage(Blocks.ENDER_CHEST, new ItemStack(Blocks.OBSIDIAN, 8), Items.ENDER_EYE);
		Salvage.addSalvage(Blocks.OAK_FENCE, new ItemStack(Items.STICK, 3));
		Salvage.addSalvage(Blocks.SPRUCE_FENCE, new ItemStack(Items.STICK, 3));
		Salvage.addSalvage(Blocks.BIRCH_FENCE, new ItemStack(Items.STICK, 3));
		Salvage.addSalvage(Blocks.JUNGLE_FENCE, new ItemStack(Items.STICK, 3));
		Salvage.addSalvage(Blocks.DARK_OAK_FENCE, new ItemStack(Items.STICK, 3));
		Salvage.addSalvage(Blocks.ACACIA_FENCE, new ItemStack(Items.STICK, 3));
		Salvage.addSalvage(Blocks.OAK_FENCE_GATE, new ItemStack(Items.STICK, 3));
		Salvage.addSalvage(Blocks.SPRUCE_FENCE_GATE, new ItemStack(Items.STICK, 3));
		Salvage.addSalvage(Blocks.BIRCH_FENCE_GATE, new ItemStack(Items.STICK, 3));
		Salvage.addSalvage(Blocks.JUNGLE_FENCE_GATE, new ItemStack(Items.STICK, 3));
		Salvage.addSalvage(Blocks.DARK_OAK_FENCE_GATE, new ItemStack(Items.STICK, 3));
		Salvage.addSalvage(Blocks.ACACIA_FENCE_GATE, new ItemStack(Items.STICK, 3));
		Salvage.addSalvage(Blocks.GOLDEN_RAIL, Items.GOLD_INGOT);
		Salvage.addSalvage(Blocks.HEAVY_WEIGHTED_PRESSURE_PLATE, new ItemStack(Items.IRON_INGOT, 2));
		Salvage.addSalvage(Blocks.LIGHT_WEIGHTED_PRESSURE_PLATE, new ItemStack(Items.GOLD_INGOT, 2));
		Salvage.addSalvage(Blocks.JUKEBOX, new ItemStack(Blocks.PLANKS, 8), Items.DIAMOND);
		Salvage.addSalvage(Blocks.LADDER, new ItemStack(Items.STICK, 2));
		Salvage.addSalvage(Blocks.LEVER, Items.STICK, Blocks.COBBLESTONE);
		Salvage.addSalvage(Blocks.LIT_PUMPKIN, Blocks.PUMPKIN, Blocks.TORCH);
		Salvage.addSalvage(Blocks.NOTEBLOCK, new ItemStack(Blocks.PLANKS, 8), Items.REDSTONE);
		Salvage.addSalvage(Blocks.RAIL, ironHunk);
		Salvage.addSalvage(Blocks.REDSTONE_LAMP, new ItemStack(Items.REDSTONE, 4), Blocks.GLOWSTONE);
		Salvage.addSalvage(Blocks.REDSTONE_TORCH, Items.STICK, Items.REDSTONE);
		Salvage.addSalvage(Blocks.SANDSTONE, new ItemStack(Blocks.SAND, 4));
		Salvage.addSalvage(Blocks.STONEBRICK, Blocks.STONE);
		Salvage.addSalvage(Blocks.STONE_BUTTON, Blocks.STONE);
		Salvage.addSalvage(Blocks.STONE_PRESSURE_PLATE, new ItemStack(Blocks.STONE, 2));
		Salvage.addSalvage(Blocks.TNT, new ItemStack(Blocks.SAND, 4), Items.GUNPOWDER, 5);
		Salvage.addSalvage(Blocks.TRAPPED_CHEST, Blocks.CHEST, Blocks.TRIPWIRE_HOOK);
		Salvage.addSalvage(Blocks.TRIPWIRE_HOOK, ironHunk, ironHunk);
		Salvage.addSalvage(Blocks.WOODEN_BUTTON, Blocks.PLANKS);
		Salvage.addSalvage(Blocks.WOODEN_PRESSURE_PLATE, new ItemStack(Blocks.PLANKS, 2));
		Salvage.addSalvage(Blocks.COBBLESTONE_WALL, Blocks.COBBLESTONE);
		Salvage.addSalvage(Blocks.IRON_BARS, ironHunk, ironHunk);
		Salvage.addSalvage(Items.ITEM_FRAME, new ItemStack(Items.STICK, 8), Items.LEATHER);
	}
}
